stages:
  - build

build:       
  stage: build
  allow_failure: false
  variables:
        GIT_STRATEGY: clone
        triggercommon: ""
  after_script:
    - triggercommon=${CI_JOB_STATUS}
  tags:
    - dev-express-shell
  script:
    - pwd
    - ls
    - echo $tmp
    - cp -Rf * /data_tms/gitlab-runner/express-v2/$tmp/express-root || FAILED=true
