stages:
  - build
  - sonar

build:       
  stage: build
  allow_failure: false
  variables:
        GIT_STRATEGY: clone
        triggercommon: ""
  after_script:
    - triggercommon=${CI_JOB_STATUS}
  tags:
    - dev-exp-shell
  script:
    - pwd
    - ls
    - echo $tmp
    - cp -Rf * /data_tms/gitlab-runner/express-v2/$tmp/express-root || FAILED=true

sonar:
  stage: sonar
  variables:
    GIT_STRATEGY: clone
  tags:
    - dev-exp-shell
  script:
    - docker run -u 1003:1003 --rm --network host -v `pwd`:/app --workdir="/app"  sonarsource/sonar-scanner-cli:5.0.1 sonar-scanner -X $SONAR_SCANNER_OPTS -Dsonar.host.url="$STAG_SONAR_HOST_URL" -Dsonar.login="$STAG_SONAR_TOKEN" -Dsonar.java.binaries="." -Dsonar.sources="." -Dsonar.projectKey="${CI_PROJECT_NAME}" -Dsonar.projectName="$CI_PROJECT_NAME" -Dsonar.projectVersion="${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}";
