spring.application.name=log-producer-client
spring.main.banner-mode=off

# Backend URL
producer.backend-url=http://localhost:8081/api/logs

# Producer config
producer.tps=1000
producer.batch-size=100
producer.connect-timeout-ms=3000
producer.read-timeout-ms=5000

# Suppress noise
logging.level.root=WARN
logging.level.org.example.producer=INFO